# Cloud Supabase Configuration
# All settings here are for referencing the cloud setup
# Local database is not used anymore - we now use cloud Supabase for all environments

# Different projects for each environment:
# - Development: https://wexkgcszrwxqsthahfyq.supabase.co
# - Production: https://wexkgcszrwxqsthahfyq.supabase.co
project_id = "automai-cloud"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "https://automai-eta.vercel.app"
# Update cookie settings for production
cookie_options = { 
  same_site = "lax",
  path = "/",
  secure = true,
  domain = "vercel.app"
}
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = [
  # Production URLs
  "https://automai-eta.vercel.app",
  "https://automai-eta.vercel.app/auth-redirect",
  "https://automai-eta.vercel.app/en/auth-redirect",
  "https://automai-eta.vercel.app/fr/auth-redirect",
  "https://automai-eta.vercel.app/api/auth/callback",
  "https://automai-eta.vercel.app/api/auth/callback/github",
  "https://automai-eta.vercel.app/api/auth/callback/google",
  "https://automai-eta.vercel.app/*",
  "https://wexkgcszrwxqsthahfyq.supabase.co/auth/v1/callback",
  "https://wexkgcszrwxqsthahfyq.supabase.co/auth/v1/user",
  "https://wexkgcszrwxqsthahfyq.supabase.co/*"
]

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false
# If enabled, users will need to reauthenticate or have logged in recently to change their password.
secure_password_change = false
# Controls the minimum amount of time that must pass before sending another signup confirmation or password reset email.
max_frequency = "1s"
# Number of characters used in the email OTP.
otp_length = 6
# Number of seconds before the email OTP expires (defaults to 1 hour).
otp_expiry = 3600

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = false
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false
# Template for sending OTP to users
template = "Your code is {{ .Code }}"
# Controls the minimum amount of time that must pass before sending another sms otp.
max_frequency = "5s"

[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
# DO NOT commit your Twilio auth token to git. Use environment variable substitution instead:
auth_token = "env(SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN)"

# Multi-factor-authentication is available to Supabase Pro plan.
[auth.mfa]
# Control how many MFA factors can be enrolled at once per user.
max_enrolled_factors = 10

# Control MFA via App Authenticator (TOTP)
[auth.mfa.totp]
enroll_enabled = false
verify_enabled = false

# Configure MFA via Phone Messaging
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false
otp_length = 6
template = "Your code is {{ .Code }}"
max_frequency = "5s"

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin_oidc`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.

[auth.external.github]
enabled = true
client_id = "Ov23liaMpBie6bYgkSwX"
# Use environment variable in production
secret = "env(SUPABASE_AUTH_GITHUB_SECRET)"
# Use the Supabase production auth endpoint as redirect target
redirect_uri = "https://wexkgcszrwxqsthahfyq.supabase.co/auth/v1/callback"

[auth.external.google]
enabled = true
client_id = "1004866229182-p6ribbdkmmblb0k44o5h1g5hoaddi05s.apps.googleusercontent.com"
# Use environment variable in production
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"
# Use the Supabase production auth endpoint as redirect target
redirect_uri = "https://wexkgcszrwxqsthahfyq.supabase.co/auth/v1/callback"

[auth.external.apple]
enabled = false
client_id = ""
# DO NOT commit your OAuth provider secret to git. Use environment variable substitution instead:
secret = "env(SUPABASE_AUTH_EXTERNAL_APPLE_SECRET)"
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure,
# or any other third-party OIDC providers.
url = ""
# If enabled, the nonce check will be skipped. Required for local sign in with Google auth.
skip_nonce_check = false

[edge_runtime]
enabled = false
# Configure one of the supported request policies: `oneshot`, `per_worker`.
# Use `oneshot` for hot reload, or `per_worker` for load testing.
policy = "oneshot"
# Port to attach the Chrome inspector for debugging edge functions.
inspector_port = 8083

[analytics]
enabled = false
port = 54327
# Configure one of the supported backends: `postgres`, `bigquery`.
backend = "postgres"

# Experimental features may be deprecated any time
[experimental]
# Configures Postgres storage engine to use OrioleDB (S3)
orioledb_version = ""
# Configures S3 bucket URL, eg. <bucket_name>.s3-<region>.amazonaws.com
s3_host = "env(S3_HOST)"
# Configures S3 bucket region, eg. us-east-1
s3_region = "env(S3_REGION)"
# Configures AWS_ACCESS_KEY_ID for S3 bucket
s3_access_key = "env(S3_ACCESS_KEY)"
# Configures AWS_SECRET_ACCESS_KEY for S3 bucket
s3_secret_key = "env(S3_SECRET_KEY)"