export const androidTvRemoteConfig = {
  remote_info: {
    name: 'Android TV',
    type: 'android_tv' as const,
    image_url: '/android-tv-remote.png',
    default_scale: 1,
    min_scale: 0.3,
    max_scale: 1.0,
    button_scale_factor: 4,
    global_offset: { x: 0, y: 0 },
    text_style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: 'white',
      textShadow: '2px 2px 4px rgba(0,0,0,0.9)',
    },
  },
  panel_layout: {
    collapsed: {
      width: '160px',
      height: '300px',
      position: {
        bottom: '20px',
        right: '20px',
      },
    },
    expanded: {
      width: '240px',
      height: '600px',
      position: {
        top: '100px',
        right: '20px',
      },
    },
    zIndex: 1000,
    showScreenshotInCollapsed: false,
    showScreenshotInExpanded: true,
    header: {
      height: '48px',
      fontSize: '0.875rem',
      fontWeight: 'bold',
      iconSize: 'small',
      padding: '8px',
      backgroundColor: '#1E1E1E',
      borderColor: '#333',
      textColor: '#ffffff',
    },
  },
  remote_layout: {
    collapsed: {
      width: '250px',
      height: '150px',
      scale: 1,
      padding: '25px',
    },
    expanded: {
      width: '400px',
      height: '300px',
      scale: 1.0,
      padding: '50px',
    },
    background_image: {
      url: '/android-tv-remote.png',
      width: 400,
      height: 300,
    },
    global_offset: {
      x: 0,
      y: 0,
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      label: 'PWR',
      position: { x: 110, y: 70 },
      size: { width: 14, height: 14 },
      shape: 'circle' as const,
      comment: 'Power button',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 210, y: 256 },
      size: { width: 18, height: 14 },
      shape: 'rectangle' as const,
      comment: 'Navigation up',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 100, y: 360 },
      size: { width: 14, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Navigation left',
    },
    nav_center: {
      key: 'SELECT',
      label: 'OK',
      position: { x: 160, y: 310 },
      size: { width: 45, height: 45 },
      shape: 'circle' as const,
      comment: 'Navigation center/select',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 340, y: 360 },
      size: { width: 14, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Navigation right',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 210, y: 490 },
      size: { width: 18, height: 14 },
      shape: 'rectangle' as const,
      comment: 'Navigation down',
    },
    back: {
      key: 'BACK',
      label: '←',
      position: { x: 99, y: 574 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Back button',
    },
    home: {
      key: 'HOME',
      label: '🏠',
      position: { x: 210, y: 574 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Home button',
    },
    menu: {
      key: 'MENU',
      label: '☰',
      position: { x: 318, y: 574 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Menu button',
    },
    rewind: {
      key: 'REWIND',
      label: '<<',
      position: { x: 99, y: 682 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Rewind button',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '⏯',
      position: { x: 210, y: 682 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Play/pause button',
    },
    fast_forward: {
      key: 'FAST_FORWARD',
      label: '>>',
      position: { x: 318, y: 682 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Fast forward button',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: 'V+',
      position: { x: 210, y: 790 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Volume up button',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: 'V-',
      position: { x: 210, y: 898 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Volume down button',
    },
    mute: {
      key: 'VOLUME_MUTE',
      label: 'MUTE',
      position: { x: 210, y: 1010 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Mute button',
    },
  },
  button_layout_recmodal: {
    power: {
      key: 'POWER',
      label: 'PWR',
      position: { x: 55, y: 35 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Power button',
    },
    nav_up: {
      key: 'UP',
      label: '▲',
      position: { x: 105, y: 128 },
      size: { width: 25, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Navigation up',
    },
    nav_left: {
      key: 'LEFT',
      label: '◄',
      position: { x: 50, y: 180 },
      size: { width: 20, height: 25 },
      shape: 'rectangle' as const,
      comment: 'Navigation left',
    },
    nav_center: {
      key: 'SELECT',
      label: 'OK',
      position: { x: 80, y: 155 },
      size: { width: 60, height: 60 },
      shape: 'circle' as const,
      comment: 'Navigation center/select',
    },
    nav_right: {
      key: 'RIGHT',
      label: '►',
      position: { x: 170, y: 180 },
      size: { width: 20, height: 25 },
      shape: 'rectangle' as const,
      comment: 'Navigation right',
    },
    nav_down: {
      key: 'DOWN',
      label: '▼',
      position: { x: 105, y: 245 },
      size: { width: 25, height: 20 },
      shape: 'rectangle' as const,
      comment: 'Navigation down',
    },
    back: {
      key: 'BACK',
      label: '←',
      position: { x: 50, y: 287 },
      size: { width: 30, height: 30 },
      shape: 'circle' as const,
      comment: 'Back button',
    },
    home: {
      key: 'HOME',
      label: '🏠',
      position: { x: 105, y: 287 },
      size: { width: 30, height: 30 },
      shape: 'circle' as const,
      comment: 'Home button',
    },
    menu: {
      key: 'MENU',
      label: '☰',
      position: { x: 159, y: 287 },
      size: { width: 30, height: 30 },
      shape: 'circle' as const,
      comment: 'Menu button',
    },
    rewind: {
      key: 'REWIND',
      label: '<<',
      position: { x: 50, y: 341 },
      size: { width: 30, height: 30 },
      shape: 'circle' as const,
      comment: 'Rewind button',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '⏯',
      position: { x: 105, y: 341 },
      size: { width: 30, height: 30 },
      shape: 'circle' as const,
      comment: 'Play/pause button',
    },
    fast_forward: {
      key: 'FAST_FORWARD',
      label: '>>',
      position: { x: 159, y: 341 },
      size: { width: 30, height: 30 },
      shape: 'circle' as const,
      comment: 'Fast forward button',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: 'V+',
      position: { x: 105, y: 395 },
      size: { width: 30, height: 30 },
      shape: 'circle' as const,
      comment: 'Volume up button',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: 'V-',
      position: { x: 105, y: 449 },
      size: { width: 30, height: 30 },
      shape: 'circle' as const,
      comment: 'Volume down button',
    },
    mute: {
      key: 'VOLUME_MUTE',
      label: 'MUTE',
      position: { x: 105, y: 505 },
      size: { width: 30, height: 30 },
      shape: 'circle' as const,
      comment: 'Mute button',
    },
  },
} as const;

export type AndroidTvRemoteConfig = typeof androidTvRemoteConfig;
