export const androidTvRemoteConfig = {
  remote_info: {
    name: 'Fire TV Remote',
    type: 'android_tv' as const,
  },
  panel_layout: {
    collapsed: {
      width: '180px',
      height: '220px',
      position: {
        bottom: '20px',
        right: '20px',
      },
    },
    expanded: {
      width: '320px',
      height: 'calc(100vh - 140px)',
      position: {
        top: '100px',
        right: '20px',
      },
    },
    zIndex: 1000,
    showScreenshotInCollapsed: false,
    showScreenshotInExpanded: false,
  },
  remote_layout: {
    collapsed: {
      width: '140px',
      height: '180px',
      scale: 0.7,
      padding: '20px',
    },
    expanded: {
      width: '250px',
      height: '400px',
      scale: 1.0,
      padding: '35px',
    },
    background_image: {
      url: '/android-tv-remote.png',
      width: 250,
      height: 400,
    },
    global_offset: {
      x: -15,
      y: -35,
    },
    text_style: {
      fontSize: '14px',
      fontWeight: 'bold',
      color: 'white',
      textShadow: '2px 2px 4px rgba(0,0,0,0.9)',
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      label: 'PWR',
      position: { x: 41, y: 60 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'Power button',
    },
    voice: {
      key: 'VOICE_ASSIST',
      label: 'MIC',
      position: { x: 68, y: 82 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'Voice/microphone button',
    },
    nav_up: {
      key: 'DPAD_UP',
      label: '▲',
      position: { x: 68, y: 107 },
      size: { width: 25, height: 12 },
      shape: 'rectangle' as const,
      comment: 'Navigation up',
    },
    nav_left: {
      key: 'DPAD_LEFT',
      label: '◄',
      position: { x: 38, y: 136 },
      size: { width: 12, height: 25 },
      shape: 'rectangle' as const,
      comment: 'Navigation left',
    },
    nav_center: {
      key: 'DPAD_CENTER',
      label: 'OK',
      position: { x: 68, y: 136 },
      size: { width: 46, height: 46 },
      shape: 'circle' as const,
      comment: 'Navigation center/select',
    },
    nav_right: {
      key: 'DPAD_RIGHT',
      label: '►',
      position: { x: 99, y: 135 },
      size: { width: 12, height: 25 },
      shape: 'rectangle' as const,
      comment: 'Navigation right',
    },
    nav_down: {
      key: 'DPAD_DOWN',
      label: '▼',
      position: { x: 68, y: 166 },
      size: { width: 25, height: 12 },
      shape: 'rectangle' as const,
      comment: 'Navigation down',
    },
    back: {
      key: 'BACK',
      label: '←',
      position: { x: 40, y: 191 },
      size: { width: 18, height: 18 },
      shape: 'circle' as const,
      comment: 'Back button',
    },
    home: {
      key: 'HOME',
      label: '🏠',
      position: { x: 68, y: 191 },
      size: { width: 21, height: 21 },
      shape: 'circle' as const,
      comment: 'Home button',
    },
    menu: {
      key: 'MENU',
      label: '☰',
      position: { x: 96, y: 191 },
      size: { width: 21, height: 21 },
      shape: 'circle' as const,
      comment: 'Menu button',
    },
    rewind: {
      key: 'MEDIA_REWIND',
      label: '<<',
      position: { x: 40, y: 219 },
      size: { width: 21, height: 21 },
      shape: 'circle' as const,
      comment: 'Rewind button',
    },
    play_pause: {
      key: 'MEDIA_PLAY_PAUSE',
      label: '⏯',
      position: { x: 68, y: 219 },
      size: { width: 21, height: 21 },
      shape: 'circle' as const,
      comment: 'Play/pause button',
    },
    fast_forward: {
      key: 'MEDIA_FAST_FORWARD',
      label: '>>',
      position: { x: 96, y: 219 },
      size: { width: 21, height: 21 },
      shape: 'circle' as const,
      comment: 'Fast forward button',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: 'V+',
      position: { x: 68, y: 248 },
      size: { width: 21, height: 21 },
      shape: 'circle' as const,
      comment: 'Volume up button',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: 'V-',
      position: { x: 68, y: 275 },
      size: { width: 21, height: 21 },
      shape: 'circle' as const,
      comment: 'Volume down button',
    },
    mute: {
      key: 'VOLUME_MUTE',
      label: 'MUTE',
      position: { x: 68, y: 302 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'Mute button',
    },
  },
} as const;

export type AndroidTvRemoteConfig = typeof androidTvRemoteConfig;
