//DO NOT EDIT THIS FILE
import { NextRequest, NextResponse } from 'next/server';

import { updateSession, createClient } from '@/lib/supabase/middleware';

import { locales, defaultLocale } from './config';

// Lazy-loaded intl middleware
let intlMiddleware: any = null;
async function getIntlMiddleware() {
  if (!intlMiddleware) {
    const { default: createIntlMiddleware } = await import('next-intl/middleware');
    intlMiddleware = createIntlMiddleware({
      locales,
      defaultLocale,
      localePrefix: 'always',
    });
  }
  return intlMiddleware;
}

// Public paths (no auth required)
const PUBLIC_PATHS = [
  '/',
  '/features',
  '/pricing',
  '/docs',
  '/signup',
  '/auth-redirect',
  '/forgot-password',
  '/reset-password',
  '/login',
];

// Check if path is a login path
function isLoginPath(path: string): boolean {
  return path === '/login' || path.endsWith('/login');
}

// Handle login redirects for authenticated users
async function handleLoginPath(request: NextRequest) {
  // Allow login with code parameter (for OAuth callbacks)
  if (request.nextUrl.searchParams.has('code') || request.nextUrl.searchParams.has('error')) {
    console.log(
      '[MIDDLEWARE] Bypassing auth check for login path with code/error param:',
      request.nextUrl.pathname,
    );
    return NextResponse.next();
  }

  // Check if user is authenticated and redirect to dashboard if they are
  const { supabase, response: _response } = createClient(request);
  const { data, error } = await supabase.auth.getUser();

  if (error) {
    console.log('[MIDDLEWARE] Auth error on login path:', error.message);
    return NextResponse.next();
  }

  if (data.user) {
    // User is authenticated, redirect to dashboard
    const locale = request.nextUrl.pathname.split('/')[1] || defaultLocale;
    const tenantName = data.user.user_metadata?.tenant_name || 'trial';
    console.log('[MIDDLEWARE] User already authenticated, redirecting from login to dashboard');
    return NextResponse.redirect(new URL(`/${locale}/${tenantName}/dashboard`, request.url));
  }

  // Not authenticated, allow access to login page
  return NextResponse.next();
}

export default async function middleware(request: NextRequest) {
  const path = request.nextUrl.pathname;
  console.log('[MIDDLEWARE] Processing path:', path);

  // Special handling for login path
  if (isLoginPath(path)) {
    console.log('[MIDDLEWARE] Handling login path');
    return handleLoginPath(request);
  }

  // Public paths: apply locale but RETURN EARLY
  const isPublicPath = PUBLIC_PATHS.some((p) => path === p || path === `/${defaultLocale}${p}`);
  if (isPublicPath) {
    // Special handling for root path to prevent double locale
    if (path === '/') {
      console.log('[MIDDLEWARE] Handling root path');
      return NextResponse.redirect(new URL(`/${defaultLocale}`, request.url));
    }
    console.log('[MIDDLEWARE] Handling public path:', path);
    return NextResponse.next();
  }

  // Check for auth-redirect path with locale
  if (path.includes('/auth-redirect')) {
    console.log('[MIDDLEWARE] Bypassing auth check for auth-redirect path:', path);
    return NextResponse.next();
  }

  // API routes: enforce auth
  if (path.startsWith('/api/')) {
    console.log('[MIDDLEWARE] Handling API route:', path);
    return NextResponse.next();
  }

  // Protected routes: enforce locale and auth
  const hasLocale = locales.some((locale) => path.startsWith(`/${locale}/`));
  if (!hasLocale) {
    console.log('[MIDDLEWARE] Redirecting to default locale:', path);
    return NextResponse.redirect(new URL(`/${defaultLocale}${path}`, request.url));
  }

  // Check authentication directly first to avoid redirect loops
  const { supabase } = createClient(request);
  const { data, error } = await supabase.auth.getUser();

  if (error || !data.user) {
    console.log('[MIDDLEWARE] Authentication failed:', error?.message || 'No user found');
    const locale = path.split('/')[1] || defaultLocale;
    return NextResponse.redirect(new URL(`/${locale}/login`, request.url));
  }

  // User is authenticated, update the session
  const response = await updateSession(request);

  // Apply intl for authenticated users
  const intl = await getIntlMiddleware();
  return intl(response);
}

export const config = {
  matcher: [
    '/((?!_next/static|_next/image|avatars|favicon.ico).*)',
    '/(fr|en)/:path*',
    '/api/:path*',
    '/',
  ],
};
